const baseLocation = [
    { id: '0', label: 'Other non-usa' },
    { id: '1', label: 'Alabama' },
    { id: '2', label: 'Kentucky' },
    { id: '3', label: 'Ohio' },
    { id: '4', label: 'Alaska' },
    { id: '5', label: 'Louisiana' },
    { id: '6', label: 'Oklahoma' },
    { id: '7', label: 'American Samoa' },
    { id: '8', label: 'Maine' },
    { id: '9', label: 'Oregon' },
    { id: '10', label: 'Arizona' },
    { id: '11', label: 'Maryland' },
    { id: '12', label: 'Pennsylvania' },
    { id: '13', label: 'Arkansas' },
    { id: '14', label: 'Massachusetts' },
    { id: '15', label: 'Puerto Rico' },
    { id: '16', label: 'California' },
    { id: '17', label: 'Michigan' },
    { id: '18', label: 'Rhode Island' },
    { id: '19', label: 'Colorado' },
    { id: '20', label: 'Minnesota' },
    { id: '21', label: 'South Carolina' },
    { id: '22', label: 'Connecticut' },
    { id: '23', label: 'Mississippi' },
    { id: '24', label: 'South Dakota' },
    { id: '25', label: 'Delaware' },
    { id: '26', label: 'Missouri' },
    { id: '27', label: 'Tennessee' },
    { id: '28', label: 'District of Columbia' },
    { id: '29', label: 'Montana' },
    { id: '30', label: 'Texas' },
    { id: '31', label: 'Florida' },
    { id: '32', label: 'Nebraska' },
    { id: '33', label: 'United States Minor Outlying Islands' },
    { id: '34', label: 'Georgia' },
    { id: '35', label: 'Nevada' },
    { id: '36', label: 'Utah' },
    { id: '37', label: 'Guam' },
    { id: '38', label: 'New Hampshire' },
    { id: '39', label: 'Vermont' },
    { id: '40', label: 'Hawaii' },
    { id: '41', label: 'New Jersey' },
    { id: '42', label: 'Virgin Islands' },
    { id: '43', label: 'Idaho' },
    { id: '44', label: 'New Mexico' },
    { id: '45', label: 'Virginia' },
    { id: '46', label: 'Illinois' },
    { id: '47', label: 'New York' },
    { id: '48', label: 'Washington' },
    { id: '49', label: 'Indiana' },
    { id: '50', label: 'North Carolina' },
    { id: '51', label: 'West Virginia' },
    { id: '52', label: 'Iowa' },
    { id: '53', label: 'North Dakota' },
    { id: '54', label: 'Wisconsin' },
    { id: '55', label: 'Kansas' },
    { id: '56', label: 'Northern Mariana Islands' },
    { id: '57', label: 'Wyoming' }
];

export default baseLocation;
