const countryList = [
    { id: '1', label: 'United States' },
    { id: '2', label: 'Åland Islands' },
    { id: '3', label: 'Afghanistan' },
    { id: '4', label: 'Albania' },
    { id: '5', label: 'Algeria' },
    { id: '6', label: 'American Samoa' },
    { id: '7', label: 'Andorra' },
    { id: '8', label: 'Angola' },
    { id: '9', label: 'Anguilla' },
    { id: '10', label: 'Antarctica' },
    { id: '11', label: 'Antigua and Barbuda' },
    { id: '12', label: 'Argentina' },
    { id: '13', label: 'Armenia' },
    { id: '14', label: 'Aruba' },
    { id: '15', label: 'Australia' },
    { id: '16', label: 'Austria' },
    { id: '17', label: 'Azerbaijan' },
    { id: '18', label: 'Bahamas' },
    { id: '19', label: 'Bahrain' },
    { id: '20', label: 'Bangladesh' },
    { id: '21', label: 'Barbados' },
    { id: '22', label: 'Belarus' },
    { id: '23', label: 'Belgium' },
    { id: '24', label: 'Belize' },
    { id: '25', label: 'Benin' },
    { id: '26', label: 'Bermuda' },
    { id: '27', label: 'Bhutan' },
    { id: '28', label: 'Bolivia' },
    { id: '29', label: 'Bosnia and Herzegovina' },
    { id: '30', label: 'Botswana' },
    { id: '31', label: 'Bouvet Island' },
    { id: '32', label: 'Brazil' },
    { id: '33', label: 'British Indian Ocean Territory' },
    { id: '34', label: 'Brunei Darussalam' },
    { id: '35', label: 'Bulgaria' },
    { id: '36', label: 'Burkina Faso' },
    { id: '37', label: 'Burundi' },
    { id: '38', label: 'Cambodia' },
    { id: '39', label: 'Cameroon' },
    { id: '40', label: 'Canada' },
    { id: '41', label: 'Cape Verde' },
    { id: '42', label: 'Cayman Islands' },
    { id: '43', label: 'Central African Republic' },
    { id: '44', label: 'Chad' },
    { id: '45', label: 'Chile' },
    { id: '46', label: 'China' },
    { id: '47', label: 'Christmas Island' },
    { id: '48', label: 'Cocos (Keeling) Islands' },
    { id: '49', label: 'Colombia' },
    { id: '50', label: 'Comoros' },
    { id: '51', label: 'Congo' },
    { id: '52', label: 'Congo, The Democratic Republic Of The' },
    { id: '53', label: 'Cook Islands' },
    { id: '54', label: 'Costa Rica' },
    { id: '55', label: 'Croatia' },
    { id: '56', label: 'Cuba' },
    { id: '57', label: 'Cyprus' },
    { id: '58', label: 'Czech Republic' },
    { id: '59', label: "Côte D'Ivoire" },
    { id: '60', label: 'Denmark' },
    { id: '61', label: 'Djibouti' },
    { id: '62', label: 'Dominica' },
    { id: '63', label: 'Dominican Republic' },
    { id: '64', label: 'Ecuador' },
    { id: '65', label: 'Egypt' },
    { id: '66', label: 'El Salvador' },
    { id: '67', label: 'Equatorial Guinea' },
    { id: '68', label: 'Eritrea' },
    { id: '69', label: 'Estonia' },
    { id: '70', label: 'Ethiopia' },
    { id: '71', label: 'Falkland Islands (Malvinas)' },
    { id: '72', label: 'Faroe Islands' },
    { id: '73', label: 'Fiji' },
    { id: '74', label: 'Finland' },
    { id: '75', label: 'France' },
    { id: '76', label: 'French Guiana' },
    { id: '77', label: 'French Polynesia' },
    { id: '78', label: 'French Southern Territories' },
    { id: '79', label: 'Gabon' },
    { id: '80', label: 'Gambia' },
    { id: '81', label: 'Georgia' },
    { id: '82', label: 'Germany' },
    { id: '83', label: 'Ghana' },
    { id: '84', label: 'Gibraltar' },
    { id: '85', label: 'Greece' },
    { id: '86', label: 'Greenland' },
    { id: '87', label: 'Grenada' },
    { id: '88', label: 'Guadeloupe' },
    { id: '89', label: 'Guam' },
    { id: '90', label: 'Guatemala' },
    { id: '91', label: 'Guernsey' },
    { id: '92', label: 'Guinea' },
    { id: '93', label: 'Guinea-Bissau' },
    { id: '94', label: 'Guyana' },
    { id: '95', label: 'Haiti' },
    { id: '96', label: 'Heard and McDonald Islands' },
    { id: '97', label: 'Holy See (Vatican City State)' },
    { id: '98', label: 'Honduras' },
    { id: '99', label: 'Hong Kong' },
    { id: '100', label: 'Hungary' },
    { id: '101', label: 'Iceland' },
    { id: '102', label: 'India' },
    { id: '103', label: 'Indonesia' },
    { id: '104', label: 'Iran, Islamic Republic Of' },
    { id: '105', label: 'Iraq' },
    { id: '106', label: 'Ireland' },
    { id: '107', label: 'Isle of Man' },
    { id: '108', label: 'Israel' },
    { id: '109', label: 'Italy' },
    { id: '110', label: 'Jamaica' },
    { id: '111', label: 'Japan' },
    { id: '112', label: 'Jersey' },
    { id: '113', label: 'Jordan' },
    { id: '114', label: 'Kazakhstan' },
    { id: '115', label: 'Kenya' },
    { id: '116', label: 'Kiribati' },
    { id: '117', label: "Korea, Democratic People's Republic Of" },
    { id: '118', label: 'Korea, Republic of' },
    { id: '119', label: 'Kuwait' },
    { id: '120', label: 'Kyrgyzstan' },
    { id: '121', label: "Lao People's Democratic Republic" },
    { id: '122', label: 'Latvia' },
    { id: '123', label: 'Lebanon' },
    { id: '124', label: 'Lesotho' },
    { id: '125', label: 'Liberia' },
    { id: '126', label: 'Libyan Arab Jamahiriya' },
    { id: '127', label: 'Liechtenstein' },
    { id: '128', label: 'Lithuania' },
    { id: '129', label: 'Luxembourg' },
    { id: '130', label: 'Macao' },
    { id: '131', label: 'Macedonia, the Former Yugoslav Republic Of' },
    { id: '132', label: 'Madagascar' },
    { id: '133', label: 'Malawi' },
    { id: '134', label: 'Malaysia' },
    { id: '135', label: 'Maldives' },
    { id: '136', label: 'Mali' },
    { id: '137', label: 'Malta' },
    { id: '138', label: 'Marshall Islands' },
    { id: '139', label: 'Martinique' },
    { id: '140', label: 'Mauritania' },
    { id: '141', label: 'Mauritius' },
    { id: '142', label: 'Mayotte' },
    { id: '143', label: 'Mexico' },
    { id: '144', label: 'Micronesia, Federated States Of' },
    { id: '145', label: 'Moldova, Republic of' },
    { id: '146', label: 'Monaco' },
    { id: '147', label: 'Mongolia' },
    { id: '148', label: 'Montenegro' },
    { id: '149', label: 'Montserrat' },
    { id: '150', label: 'Morocco' },
    { id: '151', label: 'Mozambique' },
    { id: '152', label: 'Myanmar' },
    { id: '153', label: 'Namibia' },
    { id: '154', label: 'Nauru' },
    { id: '155', label: 'Nepal' },
    { id: '156', label: 'Netherlands' },
    { id: '157', label: 'Netherlands Antilles' },
    { id: '158', label: 'New Caledonia' },
    { id: '159', label: 'New Zealand' },
    { id: '160', label: 'Nicaragua' },
    { id: '161', label: 'Niger' },
    { id: '162', label: 'Nigeria' },
    { id: '163', label: 'Niue' },
    { id: '164', label: 'Norfolk Island' },
    { id: '165', label: 'Northern Mariana Islands' },
    { id: '166', label: 'Norway' },
    { id: '167', label: 'Oman' },
    { id: '168', label: 'Pakistan' },
    { id: '169', label: 'Palau' },
    { id: '170', label: 'Palestinian Territory, Occupied' },
    { id: '171', label: 'Panama' },
    { id: '172', label: 'Papua New Guinea' },
    { id: '173', label: 'Paraguay' },
    { id: '174', label: 'Peru' },
    { id: '175', label: 'Philippines' },
    { id: '176', label: 'Pitcairn' },
    { id: '177', label: 'Poland' },
    { id: '178', label: 'Portugal' },
    { id: '179', label: 'Puerto Rico' },
    { id: '180', label: 'Qatar' },
    { id: '181', label: 'Romania' },
    { id: '182', label: 'Russian Federation' },
    { id: '183', label: 'Rwanda' },
    { id: '184', label: 'Réunion' },
    { id: '185', label: 'Saint Barthélemy' },
    { id: '186', label: 'Saint Helena' },
    { id: '187', label: 'Saint Kitts And Nevis' },
    { id: '188', label: 'Saint Lucia' },
    { id: '189', label: 'Saint Martin' },
    { id: '190', label: 'Saint Pierre And Miquelon' },
    { id: '191', label: 'Saint Vincent And The Grenedines' },
    { id: '192', label: 'Samoa' },
    { id: '193', label: 'San Marino' },
    { id: '194', label: 'Sao Tome and Principe' },
    { id: '195', label: 'Saudi Arabia' },
    { id: '196', label: 'Senegal' },
    { id: '197', label: 'Serbia' },
    { id: '198', label: 'Seychelles' },
    { id: '199', label: 'Sierra Leone' },
    { id: '200', label: 'Singapore' },
    { id: '201', label: 'Slovakia' },
    { id: '202', label: 'Slovenia' },
    { id: '203', label: 'Solomon Islands' },
    { id: '204', label: 'Somalia' },
    { id: '205', label: 'South Africa' },
    { id: '206', label: 'South Georgia and the South Sandwich Islands' },
    { id: '207', label: 'Spain' },
    { id: '208', label: 'Sri Lanka' },
    { id: '209', label: 'Sudan' },
    { id: '210', label: 'Suriname' },
    { id: '211', label: 'Svalbard And Jan Mayen' },
    { id: '212', label: 'Swaziland' },
    { id: '213', label: 'Sweden' },
    { id: '214', label: 'Switzerland' },
    { id: '215', label: 'Syrian Arab Republic' },
    { id: '216', label: 'Taiwan, Province Of China' },
    { id: '217', label: 'Tajikistan' },
    { id: '218', label: 'Tanzania, United Republic of' },
    { id: '219', label: 'Thailand' },
    { id: '220', label: 'Timor-Leste' },
    { id: '221', label: 'Togo' },
    { id: '222', label: 'Tokelau' },
    { id: '223', label: 'Tonga' },
    { id: '224', label: 'Trinidad and Tobago' },
    { id: '225', label: 'Tunisia' },
    { id: '226', label: 'Turkey' },
    { id: '227', label: 'Turkmenistan' },
    { id: '228', label: 'Turks and Caicos Islands' },
    { id: '229', label: 'Tuvalu' },
    { id: '230', label: 'Uganda' },
    { id: '231', label: 'Ukraine' },
    { id: '232', label: 'United Arab Emirates' },
    { id: '233', label: 'United Kingdom' },
    { id: '234', label: 'United States Minor Outlying Islands' },
    { id: '235', label: 'Uruguay' },
    { id: '236', label: 'Uzbekistan' },
    { id: '237', label: 'Vanuatu' },
    { id: '238', label: 'Venezuela, Bolivarian Republic of' },
    { id: '239', label: 'Viet Nam' },
    { id: '240', label: 'Virgin Islands, British' },
    { id: '241', label: 'Virgin Islands, U.S.' },
    { id: '242', label: 'Wallis and Futuna' },
    { id: '243', label: 'West Indies' },
    { id: '244', label: 'Western Sahara' },
    { id: '245', label: 'Yemen' },
    { id: '246', label: 'Zambia' },
    { id: '247', label: 'Zimbabwe' }
];

export default countryList;
