const healthPlanList = [
    { id: '1', label: 'Aetna via NaviNet' },
    { id: '2', label: 'Amerigroup Corporation' },
    { id: '3', label: 'Amplifon Hearing Health Care' },
    { id: '4', label: 'Avesis Incorporated' },
    { id: '5', label: 'Cenpatico' },
    { id: '6', label: 'Columbia United Providers' },
    { id: '7', label: 'Coordinated Care' },
    { id: '8', label: 'Coventry Health Care Workers Compensation Inc' },
    { id: '9', label: 'DentalQuest' },
    { id: '10', label: 'First Choice Health' },
    { id: '11', label: 'Great Rivers Behavioral Health Organization' },
    { id: '12', label: 'Health Net Federal Services' },
    { id: '13', label: 'LeggUP Inc.' },
    { id: '14', label: 'MCNA Dental' },
    { id: '15', label: 'National Vision' },
    { id: '16', label: 'Optum - Behavioral Health' },
    { id: '17', label: 'Optum Care Network' },
    { id: '18', label: 'Physicians of Southwest Washington' },
    { id: '19', label: 'Premera Blue Cross' },
    { id: '20', label: 'PROGYNY' },
    { id: '21', label: 'Public Health Seattle-King County' },
    { id: '22', label: 'Regence BlueShield' },
    { id: '23', label: 'Starmount-Unum' },
    { id: '24', label: 'Therapeutic Associates' },
    { id: '25', label: 'U.S. VISION' },
    { id: '26', label: 'UnitedHealthcare - Dental' },
    { id: '27', label: 'UnitedHealthcare - Vision - Spectera Eyecare Networks' },
    { id: '28', label: 'Vision Benefits of America' },
    { id: '29', label: 'Washington Department of Labor and Industries (L&I)' },
    { id: '30', label: 'American Specialty Health' },
    { id: '31', label: 'AMERITAS' },
    { id: '32', label: 'Asuris Northwest Health' },
    { id: '33', label: 'CAREINGTON INTERNATIONAL CORPORATION' },
    { id: '34', label: 'CIGNA' },
    { id: '35', label: 'Community Health Plan of WA' },
    { id: '36', label: 'Coventry Health Care' },
    { id: '37', label: 'Delta Dental of Washington' },
    { id: '38', label: 'Eye Med Vision Care' },
    { id: '39', label: 'GEHA' },
    { id: '40', label: 'Guardian Life Insurance Company of America' },
    { id: '41', label: 'Kaiser Permanente Washington' },
    { id: '42', label: 'LifeWise Health Plan' },
    { id: '43', label: 'Molina Healthcare' },
    { id: '44', label: 'Northwest Rehab Alliance' },
    { id: '45', label: 'Optum - Physical Health' },
    { id: '46', label: 'PacificSource Health Plans (WA State only)' },
    { id: '47', label: 'Planned Parenthood of the Great Northwest and the Hawaiian Islands' },
    { id: '48', label: 'Principal Life Insurance Co-Dental' },
    { id: '49', label: 'Providence Plan Partners' },
    { id: '50', label: 'QualChoice Health Plan Services, Inc' },
    { id: '51', label: 'Star Hearing' },
    { id: '52', label: 'The CHP Group' },
    { id: '53', label: 'Tivity Health' },
    { id: '54', label: 'United Concordia Dental' },
    { id: '55', label: 'UnitedHealthcare - Medical' },
    { id: '56', label: 'Versant Health' },
    { id: '57', label: 'Vision Service Plan' },
    { id: '58', label: 'Willamette Dental Group' }
];

export default healthPlanList;
