const languagesList = [
    { id: '1', label: 'Mandarin Chinese' },
    { id: '2', label: 'Spanish' },
    { id: '3', label: 'English' },
    { id: '4', label: 'Hindi (Sanskritised Hindustani)' },
    { id: '5', label: 'Bengali' },
    { id: '6', label: 'Portuguese' },
    { id: '7', label: 'Russian' },
    { id: '8', label: 'Japanese' },
    { id: '9', label: 'Western Punjabi' },
    { id: '10', label: 'Yue Chinese' },
    { id: '11', label: 'Vietnamese' },
    { id: '12', label: 'Marathi' },
    { id: '13', label: 'Telugu' },
    { id: '14', label: 'Turkish' },
    { id: '15', label: 'Wu Chinese' },
    { id: '16', label: 'Korean' },
    { id: '17', label: 'French' },
    { id: '18', label: 'German (only Standard German)' },
    { id: '19', label: 'Tamil' },
    { id: '20', label: 'Urdu (Persianised Hindustani)' },
    { id: '21', label: 'Javanese' },
    { id: '22', label: 'Italian' },
    { id: '23', label: 'Egyptian Arabic' },
    { id: '24', label: 'Gujarati' },
    { id: '25', label: 'Iranian Persian' },
    { id: '26', label: 'Bhojpuri' },
    { id: '27', label: 'Southern Min' },
    { id: '28', label: 'Hakka' },
    { id: '29', label: 'Jin Chinese' },
    { id: '30', label: 'Hausa' },
    { id: '31', label: 'Kannada' },
    { id: '32', label: 'Indonesian' },
    { id: '33', label: 'Yoruba' },
    { id: '34', label: 'Polish' },
    { id: '35', label: 'Xiang Chinese' },
    { id: '36', label: 'Malayalam' },
    { id: '37', label: 'Odia' },
    { id: '38', label: 'Maithili' },
    { id: '39', label: 'Sudanese Arabic' },
    { id: '40', label: 'Burmese' },
    { id: '41', label: 'Eastern Punjabi' },
    { id: '42', label: 'Sunda' },
    { id: '43', label: 'Algerian Arabic' },
    { id: '44', label: 'Moroccan Arabic' },
    { id: '45', label: 'Ukrainian' },
    { id: '46', label: 'Igbo' },
    { id: '47', label: 'Northern Uzbek' },
    { id: '48', label: 'Sindhi' },
    { id: '49', label: 'North Levantine Arabic' },
    { id: '50', label: 'Romanian' },
    { id: '51', label: 'Tagalog' },
    { id: '52', label: 'Dutch' },
    { id: '53', label: 'Saʽidi Arabic' },
    { id: '54', label: 'Gan Chinese' },
    { id: '55', label: 'Amharic' },
    { id: '56', label: 'Northern Pashto' },
    { id: '57', label: 'Magahi' },
    { id: '58', label: 'Thai' },
    { id: '59', label: 'Saraiki' },
    { id: '60', label: 'Khmer' },
    { id: '61', label: 'Chhattisgarhi' },
    { id: '62', label: 'Somali' },
    { id: '63', label: 'Malaysian (Malaysian Malay)' },
    { id: '64', label: 'Cebuano' },
    { id: '65', label: 'Nepali' },
    { id: '66', label: 'Mesopotamian Arabic' },
    { id: '67', label: 'Assamese' },
    { id: '68', label: 'Sinhalese' },
    { id: '69', label: 'Northern Kurdish' },
    { id: '70', label: 'Hejazi Arabic' },
    { id: '71', label: 'Nigerian Fulfulde' },
    { id: '72', label: 'Bavarian' },
    { id: '73', label: 'South Azerbaijani' },
    { id: '74', label: 'Greek' },
    { id: '75', label: 'Chittagonian' },
    { id: '76', label: 'Kazakh' },
    { id: '77', label: 'Deccan' },
    { id: '78', label: 'Hungarian' },
    { id: '79', label: 'Kinyarwanda' },
    { id: '80', label: 'Zulu' },
    { id: '81', label: 'South Levantine Arabic' },
    { id: '82', label: 'Tunisian Arabic' },
    { id: '83', label: 'Sanaani Spoken Arabic' },
    { id: '84', label: 'Northern Min' },
    { id: '85', label: 'Southern Pashto' },
    { id: '86', label: 'Rundi' },
    { id: '87', label: 'Czech' },
    { id: '88', label: 'Taʽizzi-Adeni Arabic' },
    { id: '89', label: 'Uyghur' },
    { id: '90', label: 'Eastern Min' },
    { id: '91', label: 'Sylheti' }
];

export default languagesList;
