const licenseTypeList = [
    { id: '1', label: 'Acupuncturist or Acupuncture and Eastern Medicine Practitioner License - AC' },
    { id: '2', label: 'Acupuncturist or Acupuncture and Eastern Medicine Practitioner Temp Permit - TP' },
    { id: '3', label: 'Advanced Emergency Medical Technician Certification - ES' },
    { id: '4', label: 'Advanced Registered Nurse Practitioner Anesthetist License - AP' },
    { id: '5', label: 'Advanced Registered Nurse Practitioner Clinical Specialist License - AP' },
    { id: '6', label: 'Advanced Registered Nurse Practitioner Community Health License - AP' },
    { id: '7', label: 'Advanced Registered Nurse Practitioner Emergency Interim Permit - EP' },
    { id: '8', label: 'Advanced Registered Nurse Practitioner Enterostomal Therapy License - AP' },
    { id: '9', label: 'Advanced Registered Nurse Practitioner License - AP' },
    { id: '10', label: 'Advanced Registered Nurse Practitioner Maternal Gynecological Neonatal License - AP' },
    { id: '11', label: 'Advanced Registered Nurse Practitioner Medical Surgical - AP' },
    { id: '12', label: 'Advanced Registered Nurse Practitioner Midwife License - AP' },
    { id: '13', label: 'Advanced Registered Nurse Practitioner Neurosurgical License - AP' },
    { id: '14', label: 'Advanced Registered Nurse Practitioner Occupational Health License - AP' },
    { id: '15', label: 'Advanced Registered Nurse Practitioner School License - AP' },
    { id: '16', label: 'Advanced Registered Nurse Practitioner Temporary Practice Permit - N3' },
    { id: '17', label: 'Agency Affiliated Counselor Co-Occurring Disorder Specialist Enhancement - CG' },
    { id: '18', label: 'Airway Technician Certification - ES' },
    { id: '19', label: 'Animal Massage Certification for Large Animals - AM' },
    { id: '20', label: 'Animal Massage Certification for Small Animals - AS' },
    { id: '21', label: 'Athletic Trainer License - A1' },
    { id: '22', label: 'Athletic Trainer Temporary Practice Permit - TP' },
    { id: '23', label: 'Audiologist Certificate - CD' },
    { id: '24', label: 'Audiologist Interim Permit - AI' },
    { id: '25', label: 'Audiologist License - LD' },
    { id: '26', label: 'Audiologist Non Dispensing Certificate - NN' },
    { id: '27', label: 'Audiologist Temporary Practice Permit - TP' },
    { id: '28', label: 'Cardiovascular Invasive Specialist Certification - IS' },
    { id: '29', label: 'Certified Behavior Technician - CB' },
    { id: '30', label: 'Chiropractic Preceptorship Senior Year Student or Postgraduate Trainee - CK' },
    { id: '31', label: 'Chiropractic X-Ray Technician Registration - CX' },
    { id: '32', label: 'Chiropractor License - CH' },
    { id: '33', label: 'Chiropractor Preceptor Approval - CJ' },
    { id: '34', label: 'Chiropractor Temporary Permit - TT' },
    { id: '35', label: 'Chiropractor Thirty Day Registration - TC' },
    { id: '36', label: 'Colon Hydrotherapist Certification - TH' },
    { id: '37', label: 'Counselor Agency Affiliated Registration - CG' },
    { id: '38', label: 'Counselor Agency Affliated Temporary Practice Permit - TP' },
    { id: '39', label: 'Counselor Certified Adviser Certification - CV' },
    { id: '40', label: 'Counselor Certified Certification - CL' },
    { id: '41', label: 'Counselor Registration - RC' },
    { id: '42', label: 'Dental Anesthesia Assistant Certification - AA' },
    { id: '43', label: 'Dental Assistant Registration - D1' },
    { id: '44', label: 'Dental Hygiene Initial Limited License - IL' },
    { id: '45', label: 'Dental Hygiene Initial Limited Temporary Practice Permit - TP' },
    { id: '46', label: 'Dental Hygiene License - DH' },
    { id: '47', label: 'Dental Hygiene Renewable Limited License - HL' },
    { id: '48', label: 'Dental Hygiene Temporary Practice Permit - TP' },
    { id: '49', label: 'Dentist Faculty UW License - DF' },
    { id: '50', label: 'Dentist General Anesthesia Permit - GA' },
    { id: '51', label: 'Dentist License - DE' },
    { id: '52', label: 'Dentist Moderate Sedation Permit - D3' },
    { id: '53', label: 'Dentist Moderate Sedation with Parenteral Agents Permit - CS' },
    { id: '54', label: 'Dentist Resident Community License - RR' },
    { id: '55', label: 'Dentist Resident Postdoctoral License - DR' },
    { id: '56', label: 'Dentist Temporary Practice Permit - TP' },
    { id: '57', label: 'Denturist Alternate Location - AL' },
    { id: '58', label: 'Denturist License - DN' },
    { id: '59', label: 'Denturist Temporary Practice Permit - TP' },
    { id: '60', label: 'Dietitian Certification - DI' },
    { id: '61', label: 'Dietitian Temporary Practice Permit - TP' },
    { id: '62', label: 'Drug Controlled Substance Researcher Registration - FX' },
    { id: '63', label: 'Emergency Medical Responder Certification - ES' },
    { id: '64', label: 'Emergency Medical Technician Certification - ES' },
    { id: '65', label: 'EMS Evaluator - ES' },
    { id: '66', label: 'Expanded Function Dental Auxiliary - D2' },
    { id: '67', label: 'Genetic Counselor License - GT' },
    { id: '68', label: 'Genetic Counselor Provisional License - GP' },
    { id: '69', label: 'Graduate Registered Nurse Practitioner Interim Permit - IP' },
    { id: '70', label: 'Health Care Assistant Certification - HC' },
    { id: '71', label: 'Hearing Aid Fitter Dispenser Temporary Permit - HH' },
    { id: '72', label: 'Hearing Aid Fitter Dispenser Trainee - HR' },
    { id: '73', label: 'Hearing Aid Specialist License - HA' },
    { id: '74', label: 'Hypnotherapist Registration - HP' },
    { id: '75', label: 'Intermediate Life Support Technician Certification - ES' },
    { id: '76', label: 'Intermediate Life Support/Airway Technician Certification - ES' },
    { id: '77', label: 'Intravenous Therapy Technician Certification - ES' },
    { id: '78', label: 'Intravenous/Airway Technician Certification - ES' },
    { id: '79', label: 'Licensed Assistant Behavior Analyst - AB' },
    { id: '80', label: 'Licensed Behavior Analyst - BA' },
    { id: '81', label: 'Licensed Practical Nurse - LP' },
    { id: '82', label: 'Licensed Practical Nurse Emergency Interim Permit - EP' },
    { id: '83', label: 'Licensed Practical Nurse Temporary Practice Permit - N1' },
    { id: '84', label: 'Marriage & Family Counselor Certificate - MF' },
    { id: '85', label: 'Marriage and Family Therapist Associate License - MG' },
    { id: '86', label: 'Marriage and Family Therapist License - LF' },
    { id: '87', label: 'Marriage and Family Therapist Probationary License - MK' },
    { id: '88', label: 'Marriage and Family Therapist Temporary Practice Permit - TP' },
    { id: '89', label: 'Massage Therapist License - MA' },
    { id: '90', label: 'Massage Therapist Temporary Practice Permit - TP' },
    { id: '91', label: 'Medical Assistant Certification - CM' },
    { id: '92', label: 'Medical Assistant Hemodialysis Technician Certification - HT' },
    { id: '93', label: 'Medical Assistant Hemodialysis Temporary Practice Permit - TP' },
    { id: '94', label: 'Medical Assistant Interim Certification - IC' },
    { id: '95', label: 'Medical Assistant Phlebotomist Certification - PC' },
    { id: '96', label: 'Medical Assistant Registration - MR' },
    { id: '97', label: 'Medical Marijuana Consultant Certification - MJ' },
    { id: '98', label: 'Medical Program Director - ES' },
    { id: '99', label: 'Medical Program Director Delegate - ES' },
    { id: '100', label: 'Medication Assistant Endorsement - ME' },
    { id: '101', label: 'Mental Health Counselor Associate License - MC' },
    { id: '102', label: 'Mental Health Counselor Associate Temporary Practice Permit - TP' },
    { id: '103', label: 'Mental Health Counselor Certificate - MH' },
    { id: '104', label: 'Mental Health Counselor Co-Occurring Disorder Specialist Enhancement - LH' },
    { id: '105', label: 'Mental Health Counselor License - LH' },
    { id: '106', label: 'Mental Health Counselor Probationary License - MX' },
    { id: '107', label: 'Mental Health Counselor Temporary Practice Permit - TP' },
    { id: '108', label: 'MFT Co-Occurring Disorder Specialist Enhancement - LF' },
    { id: '109', label: 'Midwife In Training - MT' },
    { id: '110', label: 'Midwife License - MW' },
    { id: '111', label: 'Midwife Student Permit - SM' },
    { id: '112', label: 'Midwife Temporary Practice Permit - TP' },
    { id: '113', label: 'Midwife Trainee Certified Professional - MP' },
    { id: '114', label: 'Naturopathic Physician License - NT' },
    { id: '115', label: 'Naturopathic Physician Temporary Practice Permit - TP' },
    { id: '116', label: 'Nursing Assistant Certification - NC' },
    { id: '117', label: 'Nursing Assistant Certified Temporary Practice Permit - TP' },
    { id: '118', label: 'Nursing Assistant Registration - NA' },
    { id: '119', label: 'Nursing Home Administrator In Training Approval - NG' },
    { id: '120', label: 'Nursing Home Administrator License - NH' },
    { id: '121', label: 'Nursing Home Administrator Limited License - HP' },
    { id: '122', label: 'Nursing Home Administrator Temporary Permit - TN' },
    { id: '123', label: 'Nursing Technician Registration - NS' },
    { id: '124', label: 'Nutritionist Certification - NU' },
    { id: '125', label: 'Occupational Therapist License - OT' },
    { id: '126', label: 'Occupational Therapist Limited Permit - TL' },
    { id: '127', label: 'Occupational Therapist Temporary Permit - TT' },
    { id: '128', label: 'Occupational Therapy Assistant License - OC' },
    { id: '129', label: 'Occupational Therapy Assistant Limited Permit - LA' },
    { id: '130', label: 'Occupational Therapy Assistant Temporary Permit - LT' },
    { id: '131', label: 'Ocularist Apprentice Registration - OR' },
    { id: '132', label: 'Ocularist License - OS' },
    { id: '133', label: 'Optician Dispensing Apprentice Registration - DT' },
    { id: '134', label: 'Optician Dispensing License - DO' },
    { id: '135', label: 'Optometrist License - OD' },
    { id: '136', label: 'Optometrist Temporary Permit - OD' },
    { id: '137', label: 'Orthotist License - OI' },
    { id: '138', label: 'Osteopathic Physician & Surgeon License - OP' },
    { id: '139', label: 'Osteopathic Physician & Surgeon Limited License - OL' },
    { id: '140', label: 'Osteopathic Physician & Surgeon Temporary Permit - TO' },
    { id: '141', label: 'Osteopathic Physician and Surgeon License Interstate Medical Licensure Compact - OP' },
    { id: '142', label: 'Osteopathic Physician Assistant Interim Permit - IO' },
    { id: '143', label: 'Osteopathic Physician Assistant License - OA' },
    { id: '144', label: 'Paramedic Certification - ES' },
    { id: '145', label: 'Pharmacist Intern Registration - IR' },
    { id: '146', label: 'Pharmacist License - PH' },
    { id: '147', label: 'Pharmacist Preceptor License - PH' },
    { id: '148', label: 'Pharmacist Temporary License - P4' },
    { id: '149', label: 'Pharmacy Assistant License - VB' },
    { id: '150', label: 'Pharmacy Technician Certification - VA' },
    { id: '151', label: 'Physical Therapist Assistant Interim Permit - P3' },
    { id: '152', label: 'Physical Therapist Assistant License - P1' },
    { id: '153', label: 'Physical Therapist Assistant Temporary Permit - P2' },
    { id: '154', label: 'Physical Therapist Interim Permit - PU' },
    { id: '155', label: 'Physical Therapist License - PT' },
    { id: '156', label: 'Physical Therapist Temporary Permit - TX' },
    { id: '157', label: 'Physical Therapy Assistant Compact Privilege - P1' },
    { id: '158', label: 'Physical Therapy Compact Privilege - PT' },
    { id: '159', label: 'Physician and Surgeon Clinical Experience License - ML' },
    { id: '160', label: 'Physician And Surgeon County/City Health Department License - ML' },
    { id: '161', label: 'Physician And Surgeon Fellowship License - FE' },
    { id: '162', label: 'Physician And Surgeon Institution License - ML' },
    { id: '163', label: 'Physician And Surgeon License - MD' },
    { id: '164', label: 'Physician and Surgeon License Interstate Medical Licensure Compact - MD' },
    { id: '165', label: 'Physician And Surgeon Residency License - ML' },
    { id: '166', label: 'Physician And Surgeon Teaching Research License - TR' },
    { id: '167', label: 'Physician And Surgeon Temporary Permit - TD' },
    { id: '168', label: 'Physician Assistant Interim Permit - TA' },
    { id: '169', label: 'Physician Assistant License - PA' },
    { id: '170', label: 'Physician Assistant Temporary Permit - BG' },
    { id: '171', label: 'Podiatric Physician And Surgeon License - PO' },
    { id: '172', label: 'Podiatric Physician And Surgeon Limited License - PL' },
    { id: '173', label: 'Podiatric Physician And Surgeon Temporary Permit - TS' },
    { id: '174', label: 'Poison Center Medical Director - ES' },
    { id: '175', label: 'Poison Information Specialist Certification - ES' },
    { id: '176', label: 'Prosthetist License - PS' },
    { id: '177', label: 'Psychological Assistant/Affiliate Certificate - PQ' },
    { id: '178', label: 'Psychologist License - PY' },
    { id: '179', label: 'Psychologist Ninety Day Permit - TY' },
    { id: '180', label: 'Psychologist Probationary License - PK' },
    { id: '181', label: 'Psychologist Temporary Permit - TE' },
    { id: '182', label: 'Radiologic Technologist Certification - RT' },
    { id: '183', label: 'Radiologic Technologist Temporary Practice Permit - TP' },
    { id: '184', label: 'Radiologist Assistant Certification - RA' },
    { id: '185', label: 'Recreational Therapist Registration - RE' },
    { id: '186', label: 'Reflexologist Certification - RF' },
    { id: '187', label: 'Registered Nurse Emergency Interim Permit - EP' },
    { id: '188', label: 'Registered Nurse Interim Permit - IP' },
    { id: '189', label: 'Registered Nurse License - RN' },
    { id: '190', label: 'Registered Nurse Temporary Practice Permit - N2' },
    { id: '191', label: 'Respiratory Care Practitioner Certificate - CR' },
    { id: '192', label: 'Respiratory Care Practitioner License - LR' },
    { id: '193', label: 'Respiratory Care Practitioner Temporary Permit - CT' },
    { id: '194', label: 'Retired Volunteer Medical Worker - FX' },
    { id: '195', label: 'Senior EMS Instructor Candidate - ES' },
    { id: '196', label: 'Senior EMS Instructor Recognition - ES' },
    { id: '197', label: 'Sex Offender Treatment Provider Affiliate Certification - AF' },
    { id: '198', label: 'Sex Offender Treatment Provider Certification - FC' },
    { id: '199', label: 'Social Worker Advanced License - LW' },
    { id: '200', label: 'Social Worker Advanced Probationary License - SK' },
    { id: '201', label: 'Social Worker Advanced Temporary Practice Permit - TP' },
    { id: '202', label: 'Social Worker Associate Advanced License - SA' },
    { id: '203', label: 'Social Worker Associate Advanced Temporary Practice Permit - TP' },
    { id: '204', label: 'Social Worker Associate Independent Clinical License - SC' },
    { id: '205', label: 'Social Worker Associate Independent Clinical Temporary Practice Permit - TP' },
    { id: '206', label: 'Social Worker Certificate - SW' },
    { id: '207', label: 'Social Worker Independent Clinical License - LW' },
    { id: '208', label: 'Social Worker Independent Clinical Probationary License - SX' },
    { id: '209', label: 'Social Worker Independent Temporary Practice Permit - TP' },
    { id: '210', label: 'Speech Language Pathologist Certificate - CL' },
    { id: '211', label: 'Speech Language Pathologist Interim Permit - SI' },
    { id: '212', label: 'Speech Language Pathologist License - LL' },
    { id: '213', label: 'Speech Language Pathologist Temporary Practice Permit - TP' },
    { id: '214', label: 'Speech Language Pathology Assistant Certification - SP' },
    { id: '215', label: 'Substance Use Disorder Professional Certification - CP' },
    { id: '216', label: 'Substance Use Disorder Professional Probationary License - CK' },
    { id: '217', label: 'Substance Use Disorder Professional Temporary Practice Permit - TP' },
    { id: '218', label: 'Substance Use Disorder Professional Trainee Certification - CO' },
    { id: '219', label: 'Substance Use Disorder Professional Trainee Temporary Practice Permit - TP' },
    { id: '220', label: 'Surgical Technologist Registration - ST' },
    { id: '221', label: 'Surgical Technologist Temporary Practice Permit - TP' },
    { id: '222', label: 'Veterinary License - VT' },
    { id: '223', label: 'Veterinary Medication Clerk Registration - VM' },
    { id: '224', label: 'Veterinary Specialty License - VS' },
    { id: '225', label: 'Veterinary Technician License - AT' },
    { id: '226', label: 'Veterinary Technician Trainee Designation - VE' },
    { id: '227', label: 'Veterinary Temporary Permit - VP' },
    { id: '228', label: 'X-Ray Technician Registration - XT' },
    { id: '229', label: 'X-Ray Technician Temporary Practice Permit - TP' }
];

export default licenseTypeList;
