const primaryPractitionerTypeList = [
    { id: '1', label: 'Acupuncturist' },
    { id: '2', label: 'Alcohol/Drug Counselor' },
    { id: '3', label: 'Advance Practice Nurses' },
    { id: '4', label: 'Audiologist' },
    { id: '5', label: 'Athletic Trainer' },
    { id: '6', label: 'Biofeedback Technician' },
    { id: '7', label: 'Board Certified Assistant Behavioral Analyst' },
    { id: '8', label: 'Board Certified Behavioral Analyst' },
    { id: '9', label: 'Certified Phlebotomist' },
    { id: '10', label: 'Certified Dental Assistant' },
    { id: '11', label: 'Certified Registered Nurse Anesthetist' },
    { id: '12', label: 'Christian Science Practitioner' },
    { id: '13', label: 'Clinical Nurse Specialist' },
    { id: '14', label: 'Clinical Lab Scientist' },
    { id: '15', label: 'Clinical Psychologist' },
    { id: '16', label: 'Clinical Social Worker' },
    { id: '17', label: 'Dietician' },
    { id: '18', label: 'Dental Hygienist' },
    { id: '19', label: 'Dental Assistant' },
    { id: '20', label: 'Doctor of Chiropractic (DC)' },
    { id: '21', label: 'Doctor of Dental Medicine (DMD)' },
    { id: '22', label: 'Doctor of Dental Surgery (DDS)' },
    { id: '23', label: 'Doctor of Podiatric Medicine (DPM)' },
    { id: '24', label: 'Doctor of Education' },
    { id: '25', label: 'Licensed Clinical Social Worker' },
    { id: '26', label: 'Limited License Psychologist' },
    { id: '27', label: 'Limited License Professional Counselor' },
    { id: '28', label: 'Licensed Bachelors Social Worker' },
    { id: '29', label: 'Limited License Bachelors Social Worker' },
    { id: '30', label: 'Licensed Masters Social Worker' },
    { id: '31', label: 'Limited License Masters Social Worker' },
    { id: '32', label: 'Licensed Marriage/Family Therapist' },
    { id: '33', label: 'Licensed Medical Esthetician' },
    { id: '34', label: 'Licensed Mental Health Counselor' },
    { id: '35', label: 'Licensed Massage Therapist' },
    { id: '36', label: 'Licensed Clinical Laboratory Technologist' },
    { id: '37', label: 'Licensed Vocational Nurse' },
    { id: '38', label: 'Licensed Practical Nurse' },
    { id: '39', label: 'Limited Social Service Technician' },
    { id: '40', label: 'Marriage/Family Therapist' },
    { id: '41', label: 'Massage Therapist' },
    { id: '42', label: 'Medical Doctor (MD)' },
    { id: '43', label: 'Medical Assistant' },
    { id: '44', label: 'Midwife' },
    { id: '45', label: 'Naturopath' },
    { id: '46', label: 'Neuropsychologist' },
    { id: '47', label: 'Nurse Midwife' },
    { id: '48', label: 'Nurse Practitioner' },
    { id: '49', label: 'Nutritionist' },
    { id: '50', label: 'Occupational Therapist' },
    { id: '51', label: 'Optician' },
    { id: '52', label: 'Optometrist' },
    { id: '53', label: 'Orthopedic Technologist' },
    { id: '54', label: 'Osteopathic Doctor (DO)' },
    { id: '55', label: 'Pharmacist' },
    { id: '56', label: 'Peer Recovery Coach' },
    { id: '57', label: 'Pharmacy Technician' },
    { id: '58', label: 'Pastoral Counselor' },
    { id: '59', label: 'Phlebotomist' },
    { id: '60', label: 'PhD, Doctor of Philosophy' },
    { id: '61', label: 'Physical Therapist' },
    { id: '62', label: 'Physician Assistant' },
    { id: '63', label: 'Physical Therapist Assistant' },
    { id: '64', label: 'Professional Counselor' },
    { id: '65', label: 'Psychologist' },
    { id: '66', label: 'Recreational Therapist' },
    { id: '67', label: 'Registered Dental Assistant' },
    { id: '68', label: 'Registered Medical Assistant' },
    { id: '69', label: 'Registered Dietician' },
    { id: '70', label: 'Registered Nurse' },
    { id: '71', label: 'Registered Nurse First Assistant' },
    { id: '72', label: 'Respiratory Therapist' },
    { id: '73', label: 'Spectacle Lens Dispenser' },
    { id: '74', label: 'Substance Abuse Treatment Specialist' },
    { id: '75', label: 'Substance Abuse Prevention Specialist' },
    { id: '76', label: 'Social Service Technician' },
    { id: '77', label: 'Social Worker' },
    { id: '78', label: 'Social Services' },
    { id: '79', label: 'Speech-Language Pathologist' },
    { id: '80', label: 'Surgical Technologist' },
    { id: '81', label: 'Xray Technician' },
    { id: '82', label: 'Temporary Limited License Psychologist' },
    { id: '83', label: 'Other' }
];

export default primaryPractitionerTypeList;
